### ISSUE TITLE
//TODO: Bruh

### ISSUE THREAD

**Issue by NgLam2911** [NgLamVN/LMAO#2]
# Introduction
* This issue contains every suggested troll feature coming from other issues.
# Troll Features
- [x] No-mine: Make a player unable to mine for a set amount of time.
- [x] No-place: Make a player unable to place blocks for a set amount of time.
- [x] No-pick: Make a player unable to pickup items for a set amount of time.
- [x] Rickroll: Never Gonna Give You Up
- [x] Starve
- [ ] Fake lag
- [ ] Freeze: Freeze the player, making them unable to move. [#1]
- [ ] Rotate: The same as flipping or spinning, but with a variable degree of rotation [#1]
- [ ] Anvil Drop: Drop an anvil [#1]
- [ ] Sound spam: Editable sound name [#1]
- [ ] Greedy: spawning a ton of rare items that the player wants to pickup but he CAN'T. [#1]
- [x] Pumpkin head [#6]

# Troll tools
- [ ] Knockback stick [#1]
- [ ] Anvil drop stick (they said that commands are too slow to type...) [#1]

# Impossible
- [ ] Girlfriend troll [#5]
